algoritmo "Di maior"

//. Faça um programa que receba a idade de dez pessoas e
//que calcule e mostre a quantidade
//de pessoas com idade maior ou igual a 18 anos.

var

idade, maiores, contador: inteiro

inicio

para contador de 1 ate 10 faca
escreval(contador)
escreva("Digite a idade: ")
leia(idade)

se idade >= 18 entao
maiores<- maiores + 1
fimse

fimpara

escreval("A quantidade de pessoas maiores de 18 anos é", maiores)


fimalgoritmo
