Algoritmo "Menor numero entre 3"
// 
//  

Var

numero, menor: inteiro



Inicio
menor<-999999999


escreval("Digite um numero: ")
leia(numero)

se numero < menor entao
menor <- numero
fimse

escreval("Digite um numero: ")
leia(numero)

se numero < menor entao
menor <- numero
fimse

escreval("Digite um numero: ")
leia(numero)

se numero < menor entao
menor <- numero
fimse

escreval("O menor numero digitado é: ", menor)





Fimalgoritmo