Algoritmo "Exercicio 3"
// 
//  
// ler numero inteiro e verificar se é positivo ou negtivo
// e se é par ou impar
Var

numero: inteiro


Inicio

escreval ("Digite um número :")
leia(numero)

se numero >= 0 entao
escreva ("O numero digitado é positivo")
senao
escreva ("O numero digitado é negativo")
fimse

se numero mod 2 = 0 entao
escreva (" e é par")
senao
escreva (" e é impar")
fimse



Fimalgoritmo
